name: Reproduce problems Sudo

on: push

jobs:
  build:
    name: Build
    runs-on: macos-11
    timeout-minutes: 40
    strategy:
      fail-fast: false
      matrix:
        run-config:
          - {
              disk-name: "image1",
            }
          - {
              disk-name: "image2",
            }
          - {
              disk-name: "image3",
            }
          - {
              disk-name: "image4",
            }
          - {
              disk-name: "image5",
            }
    steps:
      - name: Print Image Label
        run: |
          ls -la /private/etc
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Execute Python
        run: |
          python3 scripts/disk_image.py
